name: flutter_riverpod_learn
description: "A new Flutter Riverpod Learn."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  dio: ^5.4.1

flutter:

  uses-material-design: true
